### ISSUE TITLE
Recommendations for checkwinner

### ISSUE THREAD

**Issue by sfogarty** [TU-CSCI2322-FL22/solver-cunnect-fo#10]
```haskell
checkFour :: Piece -> Piece -> Piece -> Piece -> Maybe Player
combineAnswers :: [Maybe Player] -> Maybe Player
checkRow :: [Piece] -> Maybe Player
checkRows :: Board -> Maybe Player
checkAcross :: [Piece] -> [Piece] -> [Piece] -> [Piece] -> Maybe Player
checkColumns :: Board -> Maybe Player 
```
to checkDiagonals -- this can be very similar to, or even using, `checkAcross`. Take 4 at a time, look for a diagonal. Probably two helper functions, one for up and one for down

For the main checkWinner function, also have a test to see if the game is over (i.e. all full). Then make a function `outcomeFor :: Maybe Player -> Bool -> Outcome`

Try to avoid hard-coding P1/P2 into any but the most simple helper functions.

**Comment by PaulRBland** [comment]
Thanks for tips & tricks!
